### ISSUE TITLE
Installed module and receive warning about version of React Native

### ISSUE THREAD

**Issue by devbriguy** [cnjon/react-native-pdf-view#15]
npm WARN react-native-pdf-view@0.3.0 requires a peer of react-native@^0.21.0 but none was installed.

I implemented the module but does not work. Is it because of this warning? 

Update: 
react-native-cli: 0.2.0
react-native: 0.23.1
npm: 3.8.3

**Comment by sibeliusseraphini** [comment]
this was fixed by this PR https://github.com/cnjon/react-native-pdf-view/pull/14
