### ISSUE TITLE
Do PDF files have to be local? Getting Error while updating 'path' with external absolute URL

### ISSUE THREAD

**Issue by vince-rowe** [cnjon/react-native-pdf-view#18]
On RN 0.26 and PDF Viewer 0.3.2, getting Error while updating 'path' of a view managed by: RCTPDFViewAndroid when using an external absolute URL https://...example.pdf etc.

Should that work as the documentation is not clear as to whether all PDF's have to be stored locally in the app to view.

Thanks,
Vince

**Comment by vince-rowe** [comment]
In case this helps anyone there are examples included in this module which demonstrate how to load the file from a URL to local storage and then view, in our case we couldn't use this particular route as the file needed authentication headers adding, so we used this module as well as Fetch blob (v0.5.0) https://github.com/wkh237/react-native-fetch-blob to grab the file, hold it in cache and then display it using PDF View.

Thanks,
Vince

**Comment by AlisonWonderlandApps** [comment]
@vince-rowe this is exactly what I am trying to achieve.. could you share code?
