### ISSUE TITLE
Native component for "RNPDFView" does not exist

### ISSUE THREAD

**Issue by kendrickkesley** [cnjon/react-native-pdf-view#22]
Hi, I get this error message on the debugger 
Native component for "RNPDFView" does not exist

And nothing comes up in the screen related to the PDFView
I'm working with IOS 

Can you help me?
Thank you

**Comment by ndcollins** [comment]
you should use rnpm.

rnpm link react-native-pdf-view

then rebuild your app with react-native run-ios

**Comment by kendrickkesley** [comment]
Thank you!

**Comment by vikaskumar122232** [comment]
Hi, I get this error message on the debugger
Native component for "RNPDFView" does not exist

And nothing comes up in the screen related to the PDFView
I'm working with android
