### ISSUE TITLE
Android PDF library is deprecated

### ISSUE THREAD

**Issue by samin** [cnjon/react-native-pdf-view#34]
`com.joanzapata.pdfview.PDFView` or https://github.com/JoanZapata/android-pdfview is deprecated. Might be interesting to change it to a more maintained library moving forward like https://github.com/barteksc/AndroidPdfViewer

**Comment by ronak301** [comment]
+1

**Comment by grahamtallen** [comment]
+ 1

**Comment by d0ptnow** [comment]
The current android pdf library is GPL licensed. This obligate us to release ALL the source code under as GPL open source.

**Comment by samin** [comment]
@d0ptnow good point

**Comment by sibelius** [comment]
done
