### ISSUE TITLE
iOS version

### ISSUE THREAD

**Issue by sibeliusseraphini** [cnjon/react-native-pdf-view#4]

**Comment by cnjon** [comment]
At the moment there are no plans for IOS version.

**Comment by sibeliusseraphini** [comment]
I will try to bridge this component - https://github.com/vfr/Reader

and later on I will try to submit a PR for this repo

what do you think?, maybe add a tag help wanted so more people could help in the bridge to iOS

**Comment by cnjon** [comment]
Very welcome your PR.
Current version in Android is base on https://github.com/JoanZapata/android-pdfview ,zoom in / zoom out   is not smooth. 
And I found MuPDF(http://mupdf.com) is a better library for Android and iOS.
But I have no time to do this.
So ,I'm very welcome you or others to help maintain.

**Comment by sibeliusseraphini** [comment]
Next week I will try to integrate my iOS version in this repo

**Comment by cnjon** [comment]
@sibeliusseraphini Thanks!

**Comment by jeduan** [comment]
would it make sense to use a WebView as a quick-n-dirty iOS counterpart?

**Comment by sibeliusseraphini** [comment]
@jeduan yeah

**Comment by cinder92** [comment]
@sibelius any update on this? thanks!

**Comment by sibelius** [comment]
@cinder92 I've started a swift implementation in this branch: https://github.com/cnjon/react-native-pdf-view/tree/feature/swift

feels free to test and improve it

**Comment by cinder92** [comment]
@sibelius but there is no PR is not? because last commit was 8 months ago...

**Comment by sibelius** [comment]
my project decided to use a webview, so I just stopped working on the bridge.

sorry about that

**Comment by cinder92** [comment]
to bad..
