### ISSUE TITLE
Can't build

### ISSUE THREAD

**Issue by jr-k** [cnjon/react-native-pdf-view#47]
Hello,

I'm trying on Android RN 0.39 and I got this when I'm trying to react-native run-android:

https://puu.sh/uqZVN/7348b54f07.png

Someone can help me ?

Thanks !

**Comment by mkoo21** [comment]
Make sure your JDK is up-to-date with your JRE (current version is 1.8), and that you are using the right android SDK level (25.* for android 7, 23 for android 6)
