### ISSUE TITLE
Duplicate interface definition for class 'RCTBridge'

### ISSUE THREAD

**Issue by Tam** [cnjon/react-native-pdf-view#52]
I'm getting the following error when trying to build to IOS, everything works great on Android.

Using React Native `0.41.2`, PDF View `^0.3.2`.

```
Duplicate interface definition for class 'RCTBridge'
In file included from /node_modules/react-native-pdf-view/RNPDFView/RNPDFViewManager.m:11:
In file included from /node_modules/react-native-pdf-view/RNPDFView/RNPDFViewManager.h:9:
In file included from ../react-native/React/Views/RCTViewManager.h:15: /react-native/React/Base/RCTEventDispatcher.h:12:9: 
In file included from /Library/Developer/Xcode/DerivedData/App-ckzthjkwdguomaavfzoksbbpuojh/Build/Products/Debug-iphoneos/include/React/RCTEventDispatcher.h:12:
/react-native/React/Base/RCTBridge.h:65:12: Previous definition is here
```

There are additional errors but they all appear to stem from (or be similar to) this one, so I've only included this one. A quick look around brings up [this](https://github.com/facebook/react-native/issues/11725), which might be useful?

**Comment by Tam** [comment]
I've tried pulling the latest codebase and everything compiles fine. A version bump (#51) would be useful!

**Comment by richardgillzdev** [comment]
Yep, +1 to this, had the same issue

**Comment by andrey-shostik** [comment]
+1
