### ISSUE TITLE
Error while udating property 'src' of a view managed by "RCTPDFViewAndroid

### ISSUE THREAD

**Issue by alexaung** [cnjon/react-native-pdf-view#63]
I alway got the error "Error while udating property 'src' of a view managed by "RCTPDFViewAndroid".

May I know how to set local file?

let pdfpath = require("../../../pdf/en/0.pdf")

<PDFView ref={(pdf)=>{this.pdfView = pdf;}}
                     src={pdfpath}
                     onLoadComplete = {(pageCount)=>{
                        this.pdfView.setNativeProps({
                            zoom: 1.5
                        });
                     }}
                     style={styles.pdf}/>

**Comment by alexaung** [comment]
Ok, I  found the issue. src only support absolute path. It can only view from device's local storage file.

**Comment by Anujmoglix** [comment]
now how to show dynamic path ?
