### ISSUE TITLE
in iOS, no onLoadComplete event

### ISSUE THREAD

**Issue by cnjon** [cnjon/react-native-pdf-view#8]
@sibeliusseraphini 
I test example in iOS, but no onLoadComplete trigger when pdf shown.

**Comment by sibeliusseraphini** [comment]
I'm working on this

**Comment by cnjon** [comment]
this is my screen shot, my Xcode version is 7.2.1.
![qq20160310](https://cloud.githubusercontent.com/assets/10810189/13670198/784bd8dc-e703-11e5-9715-864db28205e1.png)
![qq20160311](https://cloud.githubusercontent.com/assets/10810189/13670211/880c53f0-e703-11e5-8bce-6dd9858e757a.png)
![qq20160312](https://cloud.githubusercontent.com/assets/10810189/13670405/b4c4f4f0-e704-11e5-9d26-d45ac9a0f84c.png)

**Comment by ggun69** [comment]
@cnjon How can you test it? I've imported .framework but info.plist is missing so build failed

**Comment by cnjon** [comment]
@ggun69 
1.clone or download the master branch.
2.in example, run npm install
3.open example/ios/example.xcodeproj
4.run and debug.
