### ISSUE TITLE
Warning: PropTypes has been moved to a separate package

### ISSUE THREAD

**Issue by mlding** [cnjon/react-native-pdf-view#87]
When I use this lib react-native-pdf-view, there is a warning:
PropTypes has been moved to a separate package. Accessing React.PropTypes is no longer supported and will be removed completely in React 16. Use the prop-types package on npm instead.

Can someone help to fix the warning in the library?

**Comment by enieber** [comment]
@mlding this fixed in merge #95 

@sibelius this issue can be closed
